# Generated by Django 5.1.5 on 2025-01-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time_hours',
            field=models.IntegerField(default=0, help_text='Cooking time in hours.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.IntegerField(default=0, help_text='Cooking time in minutes.'),
        ),
    ]
