# Generated by Django 5.1.5 on 2025-01-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_category_description_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='instructions',
        ),
    ]
